### ISSUE TITLE
[Bug]:  traffic-editor fix bug

### ISSUE THREAD

**Issue by gmchoi96** [open-rmf/rmf#465]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

ubuntu22.04

### Open-RMF installation type

Binaries

### Open-RMF version or commit hash

2.3.0

### ROS distribution

Humble

### ROS installation type

Binaries

### Description of the bug

When I briefly tested it two weeks ago, the map loaded fine.

When editing a file with traffic-editor, only the path appears in rviz and the png file is not created. Also, I can't read the topic for /map.

If you reinstall it will return to normal.

### Steps to reproduce the bug

1.git clone https://github.com/open-rmf/rmf_demos.git
2. Check whether the map is loaded properly "ros2 launch rmf_demos office.launch.xml"
3. Check if map information is displayed properly with ‘ros2 topic echo /map’
4. To test my robot, I simply create a new map through traffic-editor. (Or proceed by modifying only the parameters of the existing office.building.yaml file)
5. If you check after building again, an error appears. The path appears, but the image and topic do not appear.

### Additional information or screenshots

![image](https://github.com/open-rmf/rmf/assets/149559257/e3e35c7d-ff0a-4a73-be39-e14a37b3c84d)

[simple_api_server-14] TypeError: Server.emit() got an unexpected keyword argument 'broadcast'
[building_map_server-3] [INFO] [1716278922.787626742] [building_map_server]: read 1794169 byte image
[building_map_server-3] Traceback (most recent call last):
[building_map_server-3]   File "/opt/ros/humble/lib/rmf_building_map_tools/building_map_server", line 33, in <module>
[building_map_server-3]     sys.exit(load_entry_point('rmf-building-map-tools==1.6.2', 'console_scripts', 'building_map_server')())
[building_map_server-3]   File "/opt/ros/humble/lib/python3.10/site-packages/building_map_server/building_map_server.py", line 339, in main
[building_map_server-3]     n = BuildingMapServer(map_path)
[building_map_server-3]   File "/opt/ros/humble/lib/python3.10/site-packages/building_map_server/building_map_server.py", line 49, in __init__
[building_map_server-3]     self.load_building_yaml(map_path)
[building_map_server-3]   File "/opt/ros/humble/lib/python3.10/site-packages/building_map_server/building_map_server.py", line 90, in load_building_yaml
[building_map_server-3]     uncompressed = building.generate_geojson()
[building_map_server-3]   File "/opt/ros/humble/lib/python3.10/site-packages/building_map/building.py", line 869, in generate_geojson
[building_map_server-3]     wgs_transformer = Transformer.from_crs(source_crs, 'EPSG:4326')
[building_map_server-3]   File "/usr/lib/python3/dist-packages/pyproj/transformer.py", line 567, in from_crs
[building_map_server-3]     cstrencode(CRS.from_user_input(crs_from).srs),
[building_map_server-3]   File "/usr/lib/python3/dist-packages/pyproj/crs/crs.py", line 479, in from_user_input
[building_map_server-3]     return cls(value, **kwargs)
[building_map_server-3]   File "/usr/lib/python3/dist-packages/pyproj/crs/crs.py", line 326, in __init__
[building_map_server-3]     self._local.crs = _CRS(self.srs)
[building_map_server-3]   File "pyproj/_crs.pyx", line 2352, in pyproj._crs._CRS.__init__
[building_map_server-3] pyproj.exceptions.CRSError: Invalid projection: : (Internal Proj Error: proj_create: unrecognized format / unknown name)
[ERROR] [building_map_server-3]: process has died [pid 16165, exit code 1, cmd '/opt/ros/humble/lib/rmf_building_map_tools/building_map_server /home/gmchoi/rmf_ws/install/rmf_demos_maps/share/rmf_demos_maps/office/office.building.yaml --ros-args --params-file /tmp/launch_params_96o0hqye'].

**Comment by mxgrey** [comment]
The steps you provided are not specific enough to recreate the problem. We would need to know exactly what actions you took in the traffic editor or what lines you modified in the yaml file to get this error.

The backtrace might be indicating that your .building.yaml file is asking for an invalid geo coordinate projection. If you modified the yaml yourself by hand then maybe a line was corrupted.
